### ISSUE TITLE
Compilation problem, with iOS SDK 4.3GM target to 4.3 device

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DoubangoTelecom/idoubs#26]
```
What steps will reproduce the problem?
1.follow the build source instruction in wiki to have the latest doubango and 
idoubs source code
2.compile the project with iOS sdk 4.3GM, target to 4.3; got the error message 
below


What is the expected output? What do you see instead?
Expected: compile and run the binary on device

Actual:(error)
============
Ld ./build/iDoubs.build/Debug-iphoneos/iDoubs.build/Objects-normal/armv7/iDoubs 
normal armv7
cd /Users/kencai/dev/iPhone/idoubs_43/mydoubs/iPhone/idoubs
setenv IPHONEOS_DEPLOYMENT_TARGET 4.3
setenv PATH 
"/Developer_4.3GM/Platforms/iPhoneOS.platform/Developer/usr/bin:/Developer_4.3GM
/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/opt/local/bi
n:/usr/local/git/bin"
/Developer_4.3GM/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2 -arch 
armv7 -isysroot 
/Developer_4.3GM/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk 
-L/Users/kencai/dev/iPhone/idoubs_43/mydoubs/iPhone/idoubs/build/Debug-iphoneos 
-L../../Doubango/thirdparties/iphone/lib/arm 
-F/Users/kencai/dev/iPhone/idoubs_43/mydoubs/iPhone/idoubs/build/Debug-iphoneos 
-filelist 
/Users/kencai/dev/iPhone/idoubs_43/mydoubs/iPhone/idoubs/./build/iDoubs.build/De
bug-iphoneos/iDoubs.build/Objects-normal/armv7/iDoubs.LinkFileList -dead_strip 
-framework Foundation -framework UIKit -lopencore-amrnb -lgsm -lavutil -lavcore 
-lswscale -lavcodec -lx264 -logg -ltheora -ltheoraenc 
-miphoneos-version-min=4.3 -lresolv -framework AddressBook -framework 
AddressBookUI -framework AudioToolbox -ltinyDAV -ltinyHTTP -ltinyIPSEC 
-ltinyMEDIA -ltinyMSRP -ltinyNET -ltinyRTP -ltinySAK -ltinySDP -ltinySIGCOMP 
-ltinySIP -ltinySMS -ltinyXCAP -framework CoreGraphics -framework AVFoundation 
-framework CoreVideo -framework CoreMedia -lsqlite3.0 -framework CFNetwork -o 
/Users/kencai/dev/iPhone/idoubs_43/mydoubs/iPhone/idoubs/./build/iDoubs.build/De
bug-iphoneos/iDoubs.build/Objects-normal/armv7/iDoubs

ld: warning: ignoring file 
../../Doubango/thirdparties/iphone/lib/arm/libopencore-amrnb.a, file was built 
for archive which is not the architecture being linked (armv7)
ld: warning: ignoring file ../../Doubango/thirdparties/iphone/lib/arm/libgsm.a, 
file was built for archive which is not the architecture being linked (armv7)
ld: warning: ignoring file 
../../Doubango/thirdparties/iphone/lib/arm/libavutil.a, file was built for 
archive which is not the architecture being linked (armv7)
ld: warning: ignoring file 
../../Doubango/thirdparties/iphone/lib/arm/libavcore.a, file was built for 
archive which is not the architecture being linked (armv7)
ld: warning: ignoring file 
../../Doubango/thirdparties/iphone/lib/arm/libswscale.a, file was built for 
archive which is not the architecture being linked (armv7)
ld: warning: ignoring file 
../../Doubango/thirdparties/iphone/lib/arm/libavcodec.a, file was built for 
archive which is not the architecture being linked (armv7)
ld: warning: ignoring file 
../../Doubango/thirdparties/iphone/lib/arm/libx264.a, file was built for 
archive which is not the architecture being linked (armv7)
ld: warning: ignoring file ../../Doubango/thirdparties/iphone/lib/arm/libogg.a, 
file was built for archive which is not the architecture being linked (armv7)
ld: warning: ignoring file 
../../Doubango/thirdparties/iphone/lib/arm/libtheora.a, file was built for 
archive which is not the architecture being linked (armv7)
ld: warning: ignoring file 
../../Doubango/thirdparties/iphone/lib/arm/libtheoraenc.a, file was built for 
archive which is not the architecture being linked (armv7)
Undefined symbols for architecture armv7:
  "_avcodec_encode_video", referenced from:
      _tdav_codec_mp4ves_encode in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_encode in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_encode in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_encode in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_encode in libtinyDAV.a(tdav_codec_h261.o)
  "_avcodec_find_decoder", referenced from:
      _tdav_codec_mp4ves_open in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_init in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_init in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_open in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_open in libtinyDAV.a(tdav_codec_h261.o)
  "_avcodec_alloc_frame", referenced from:
      _tdav_codec_mp4ves_open in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_open in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_open in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_open in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_open in libtinyDAV.a(tdav_codec_h261.o)
      _tdav_converter_video_convert in libtinyDAV.a(tdav_converter_video.o)
  "_avpicture_get_size", referenced from:
      _tdav_codec_mp4ves_open in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_mp4ves_decode in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_open in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h264_decode in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_open in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_h263_decode in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_h263p_decode in libtinyDAV.a(tdav_codec_h263.o)
      ...
  "_gsm_create", referenced from:
      _tdav_codec_gsm_open in libtinyDAV.a(tdav_codec_gsm.o)
  "_av_malloc", referenced from:
      _tdav_converter_video_convert in libtinyDAV.a(tdav_converter_video.o)
  "_Encoder_Interface_init", referenced from:
      _tdav_codec_amrnb_open in libtinyDAV.a(tdav_codec_amr.o)
  "_avcodec_alloc_context", referenced from:
      _tdav_codec_mp4ves_open in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_open in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_open in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_open in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_open in libtinyDAV.a(tdav_codec_h261.o)
  "_Decoder_Interface_exit", referenced from:
      _tdav_codec_amrnb_close in libtinyDAV.a(tdav_codec_amr.o)
      _tdav_codec_amr_deinit in libtinyDAV.a(tdav_codec_amr.o)
  "_avpicture_fill", referenced from:
      _tdav_codec_mp4ves_encode in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_encode in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_encode in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_encode in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_encode in libtinyDAV.a(tdav_codec_h261.o)
      _tdav_converter_video_convert in libtinyDAV.a(tdav_converter_video.o)
  "_Decoder_Interface_Decode", referenced from:
      _tdav_codec_amr_be_decode in libtinyDAV.a(tdav_codec_amr.o)
      _tdav_codec_amr_oa_decode in libtinyDAV.a(tdav_codec_amr.o)
  "_gsm_decode", referenced from:
      _tdav_codec_gsm_decode in libtinyDAV.a(tdav_codec_gsm.o)
     (maybe you meant: _tdav_codec_gsm_decode)
  "_sws_freeContext", referenced from:
      _tdav_converter_video_dtor in libtinyDAV.a(tdav_converter_video.o)
  "_Encoder_Interface_Encode", referenced from:
      _tdav_codec_amr_be_encode in libtinyDAV.a(tdav_codec_amr.o)
      _tdav_codec_amr_oa_encode in libtinyDAV.a(tdav_codec_amr.o)
  "_avcodec_register_all", referenced from:
      _tdav_init in libtinyDAV.a(tdav.o)
  "_av_free", referenced from:
      _tdav_codec_mp4ves_close in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_close in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_close in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_close in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_close in libtinyDAV.a(tdav_codec_h261.o)
      _tdav_converter_video_dtor in libtinyDAV.a(tdav_converter_video.o)
  "_av_init_packet", referenced from:
      _tdav_codec_mp4ves_decode in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_decode in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_decode in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_h263p_decode in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_decode in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_decode in libtinyDAV.a(tdav_codec_h261.o)
  "_avcodec_get_frame_defaults", referenced from:
      _tdav_codec_mp4ves_open in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_open in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_open in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_open in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_open in libtinyDAV.a(tdav_codec_h261.o)
  "_avpicture_layout", referenced from:
      _tdav_codec_mp4ves_decode in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_decode in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_decode in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_h263p_decode in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_decode in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_decode in libtinyDAV.a(tdav_codec_h261.o)
  "_Decoder_Interface_init", referenced from:
      _tdav_codec_amrnb_open in libtinyDAV.a(tdav_codec_amr.o)
  "_avcodec_decode_video2", referenced from:
      _tdav_codec_mp4ves_decode in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_decode in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_decode in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_h263p_decode in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_decode in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_decode in libtinyDAV.a(tdav_codec_h261.o)
  "_gsm_encode", referenced from:
      _tdav_codec_gsm_encode in libtinyDAV.a(tdav_codec_gsm.o)
     (maybe you meant: _tdav_codec_gsm_encode)
  "_avcodec_init", referenced from:
      _tdav_init in libtinyDAV.a(tdav.o)
  "_avcodec_open", referenced from:
      _tdav_codec_mp4ves_open in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_open in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_open in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_open in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_theora_decode in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_open in libtinyDAV.a(tdav_codec_h261.o)
  "_avcodec_get_context_defaults", referenced from:
      _tdav_codec_mp4ves_open in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_open in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_open in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_open in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_open in libtinyDAV.a(tdav_codec_h261.o)
  "_avcodec_find_encoder", referenced from:
      _tdav_codec_mp4ves_open in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_init in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_init in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_open in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_open in libtinyDAV.a(tdav_codec_h261.o)
  "_avcodec_close", referenced from:
      _tdav_codec_mp4ves_close in libtinyDAV.a(tdav_codec_mp4ves.o)
      _tdav_codec_h264_close in libtinyDAV.a(tdav_codec_h264.o)
      _tdav_codec_h263_close in libtinyDAV.a(tdav_codec_h263.o)
      _tdav_codec_theora_close in libtinyDAV.a(tdav_codec_theora.o)
      _tdav_codec_h261_close in libtinyDAV.a(tdav_codec_h261.o)
  "_sws_scale", referenced from:
      _tdav_converter_video_convert in libtinyDAV.a(tdav_converter_video.o)
  "_gsm_destroy", referenced from:
      _tdav_codec_gsm_close in libtinyDAV.a(tdav_codec_gsm.o)
      _tdav_codec_gsm_dtor in libtinyDAV.a(tdav_codec_gsm.o)
  "_Encoder_Interface_exit", referenced from:
      _tdav_codec_amrnb_close in libtinyDAV.a(tdav_codec_amr.o)
      _tdav_codec_amr_deinit in libtinyDAV.a(tdav_codec_amr.o)
  "_sws_getContext", referenced from:
      _tdav_converter_video_convert in libtinyDAV.a(tdav_converter_video.o)
ld: symbol(s) not found for architecture armv7
collect2: ld returned 1 exit status
============

What version of the product are you using? On what operating system?
xcode version: 3.2.6
iOS: SDK 4.3GM

Please provide any additional information below.
1. can compile with sdk 4.2 and run the binary on device and simulator
2. can compile with sdk 4.3 simulator, and run it on simulator but not the 
device 
3. tried both arm6 and arm7, got the same error message.

```

Original issue reported on code.google.com by `android...@gmail.com` on 4 Mar 2011 at 10:14
